FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

COPY ./front/package.json .
COPY ./front/package-lock.json .

# install project dependencies
RUN npm install

RUN npm install -g vue @vue/cli @vue/cli-service-global

RUN npm install vue bootstrap-vue bootstrap

COPY ./front .

EXPOSE 8080

ENTRYPOINT npm run serve
