FROM python:3.6.10

ENV dataset_path=pdfs/data.csv
ENV reader_path=reader/bert_qa.joblib

ADD requirements.txt .

RUN pip3 install -r requirements.txt
RUN pip3 install --upgrade setuptools

ADD . .

EXPOSE 5000
CMD ["sh","run.sh"]


