FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./learnfront .

# install project dependencies
RUN npm install

RUN npm install -g vue @vue/cli @vue/cli-service-global

RUN npm install vue bootstrap-vue bootstrap

EXPOSE 9080

ENTRYPOINT npm run serve --port 9080
